import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import record from '../data/animequotes.json'
import { useState, useEffect } from 'react'

export default function Quote() {
  console.log('inside Home: ', record);

  const [data, setData] = useState(record.anime);
  const [capResult, setCapResult] = useState('');
  const [inputValue, setInputValue] = useState('Default');
  const [searchResult, setSearchResult] = useState('Default');

  const showAll = async () => {
    setCapResult('ALL')
    console.log('Button Clicked')
    console.log('setCapResult is: ', capResult)
  }

  const handleBlur = (e) => {
    setInputValue(e.target.value);
    console.log('e.target.value is: ', e.target.value)
    console.log('inputValue is: ', inputValue)
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    console.log('===submit===');
    const ResultString = inputValue.charAt(0).toUpperCase() + inputValue.slice(1);
    setCapResult(ResultString)
    console.log('setCapResult is: ', capResult);
    setSearchResult(inputValue.toLowerCase())
  }

  // useEffect(() => {
  //   const result = record.find((rec) => rec.Anime.toLowerCase().includes(searchResult));
  //   if (result) {
  //     setData(result);
  //     console.log('record.anime: ', result.Anime);
  //   }
  // }, [searchResult]);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${styles.main_quote}`}>
        <div className={`${styles.bgImg} ${styles.bgImg_quote}`}></div>

        <div className={`${styles.wrapper} ${styles.wrappe_quote}`}>

          <button
            className={`${styles.click} ${styles.submitBtn}`}
            onClick={() => showAll()}>
              SHOW ALL
          </button>

          <form
            className={styles.form}
            onSubmit={handleSubmit}
            >
            <input
              className={styles.AnimenameInput}
              type="text"
              placeholder='Enter Anime Name'
              onBlur={handleBlur}
              />
              <button
                className={`${styles.click} ${styles.submitBtn}`}
                type="submit">SEARCH
              </button>
          </form>

          <div className={styles.animeNameList_container}>
            {
              record.map( (rec, index) => {
                return (
                  <div className={styles.animeNameList_wrapper}>
                    <ul
                      key={index}
                      className={styles.list}>
                      <li className={styles.list_anime}>
                          {rec.Anime}
                      </li>
                    </ul>
                  </div>
                )
              })
            }
          </div>

          {
            capResult == 'ALL' ? <h1 className={styles.title}>ALL Quotes</h1> : searchResult ? <h1 className={styles.title}>{capResult}</h1> : <></>
          }

          <div className={styles.return_body}>
            {
              record.map( (rec, index) => {
                return (
                  <div className={styles.return_wrapper}>
                    {
                      capResult == 'ALL'
                      ? //Show all data
                        <ul
                          key={index}
                          className={styles.list}>
                          <li className={styles.list_anime}>
                              {rec.Anime}
                          </li>
                          <li className={styles.list_character}>
                              {rec.Character}
                          </li>
                          <li className={styles.list_quote}>
                              "{rec.Quote}"
                          </li>
                        </ul>
                        ://Only when there is an Anime matching with input
                          rec.Anime.toLowerCase() == searchResult
                          ?//Show that inputted Anime data
                            <ul
                              key={index}
                              className={styles.list}>
                              <li className={styles.list_character}>
                                      {rec.Character}
                                  </li>
                              <li className={styles.list_quote}>
                                      "{rec.Quote}"
                                  </li>
                            </ul>
                            ://Show nothing
                              <></>
                      }
                  </div>
                )

              })
            }
          </div>


        </div> {/* .wrapper */}
      </main>
    </>
  )
}
